apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{CERTIFICATE_AUTHORITY_DATA}}
    server: {{APISERVER_URL}}
  name: kind
current-context: kind
kind: Config
preferences: {}
contexts:
- context:
    cluster: kind
    user: kind-authenticator
  name: test-authenticator
users:
- name: kind-authenticator
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - {{CLUSTER_NAME}}
      command: {{AUTHENTICATOR_BIN}}
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: {{REGION}}
      interactiveMode: IfAvailable
      provideClusterInfo: false
