name: PR From Upstream

on:
  schedule:
  - cron:  "5 22 * * 0" # Monday 10:05am NZST
  workflow_dispatch:

jobs:
  raise-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: raise-pr
      run: |
        # https://stackoverflow.com/a/27940027
        aheadCount=$(git rev-list --left-right --count origin/main...origin/upstream | awk '{print $1}')
        syncPRCount=$(gh pr list --label upstream-sync | wc --lines)
        if [[ "${aheadCount}" -gt 0 ]] && [[ "${syncPRCount}" -eq 0 ]]
        then
          gh pr create \
            --base main \
            --head upstream \
            --label upstream-sync \
            --title "PR From Upstream" \
            --body "Rebase ${aheadCount} commits from upstream"
        fi

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
