name: PR From Upstream

on:
  push:
    branches:
      - 'upstream'

jobs:
  raise-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: raise-pr
      run: gh pr create --base main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
